// Generated by CoffeeScript 1.6.3
(function() {
  var checkLoaded, getAttrib, host, interval, isPresent, loaded, onLoad, vendorName, vendors;

  loaded = false;

  interval = null;

  host = 'cdn.webglstats.com';

  /*
  scripts = document.getElementsByTagName('script')
  myscript = scripts[scripts.length-1]
  for script in scripts
      if script.src.search(host) >= 0
          src = myscript.src
          match = src.match(/#(.*)/)
          if match?
              load = parseFloat(match[1])
              if Math.random() > load
                  return
          break
  */


  vendors = [null, 'webkit', 'moz', 'ms', 'o'];

  vendorName = function(name, vendor) {
    if (vendor && vendor.length > 0) {
      return vendor + name[0].toUpperCase() + name.substr(1);
    } else {
      return name;
    }
  };

  getAttrib = function(obj, name) {
    var prop, vendor, _i, _len;
    if (obj != null) {
      for (_i = 0, _len = vendors.length; _i < _len; _i++) {
        vendor = vendors[_i];
        prop = vendorName(name, vendor);
        if (obj[prop] != null) {
          return obj[prop];
        }
      }
    }
  };

  isPresent = function(obj, name) {
    return getAttrib(obj, name) != null;
  };

  onLoad = function() {
    var flags, frame;
    if (document.removeEventListener != null) {
      document.removeEventListener('load', onLoad, false);
      document.removeEventListener('DOMContentLoaded', onLoad, false);
    }
    clearInterval(interval);
    if (!loaded) {
      loaded = true;
      frame = document.createElement('iframe');
      flags = [];
      if (isPresent(document, 'cancelFullScreen')) {
        flags.push('fullscreen');
      }
      if (isPresent(navigator, 'getGamepads')) {
        flags.push('gamepads');
      }
      if (isPresent(document.body, 'requestPointerLock')) {
        flags.push('pointerlock');
      }
      flags = flags.join(',');
      frame.src = ("//" + host + "/statframe.html#") + flags;
      frame.style.cssText = 'display: none;';
      return document.body.appendChild(frame);
    }
  };

  checkLoaded = function() {
    if (/loaded|complete/.test(document.readyState)) {
      return onLoad();
    }
  };

  if (document.addEventListener != null) {
    document.addEventListener('DOMContentLoaded', onLoad, false);
    document.addEventListener('load', onLoad, false);
  }

  if (document.readyState != null) {
    interval = setInterval(checkLoaded, 250);
  }

}).call(this);
